services:
  app:
    container_name: bookmessanger_frontend
    build: .
    ports:
      - "3007:3007"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
    environment:
      - WATCHPACK_POLLING=true